const countries_list = [
  "afghanistan",
  "albania",
  "algeria",
  "andorra",
  "angola",
  "antigua and barbuda",
  "argentina",
  "armenia",
  "austria",
  "azerbaijan",
  "bahamas",
  "bahrain",
  "bangladesh",
  "barbados",
  "belarus",
  "belgium",
  "benin",
  "bhutan",
  "bolivia",
  "bosnia",
  "brazil",
  "brunei",
  "bulgaria",
  "burkina faso",
  "cabo verde",
  "cambodia",
  "cameroon",
  "canada",
  "central african republic",
  "chad",
  "chile",
  "colombia",
  "congo (brazzaville)",
  "congo (kinshasa)",
  "costa rica",
  "cote d'ivoire",
  "croatia",
  "diamond princess",
  "cuba",
  "cyprus",
  "czechia",
  "denmark",
  "djibouti",
  "dominican republic",
  "ecuador",
  "egypt",
  "el salvador",
  "equatorial guinea",
  "eritrea",
  "estonia",
  "eswatini",
  "ethiopia",
  "fiji",
  "finland",
  "france",
  "gabon",
  "gambia",
  "georgia",
  "germany",
  "ghana",
  "greece",
  "guatemala",
  "guinea",
  "guyana",
  "haiti",
  "holy see",
  "honduras",
  "hungary",
  "iceland",
  "india",
  "indonesia",
  "iran",
  "iraq",
  "ireland",
  "israel",
  "italy",
  "jamaica",
  "japan",
  "jordan",
  "kazakhstan",
  "kenya",
  "s. korea",
  "kuwait",
  "kyrgyzstan",
  "latvia",
  "lebanon",
  "liberia",
  "liechtenstein",
  "lithuania",
  "luxembourg",
  "madagascar",
  "malaysia",
  "maldives",
  "malta",
  "mauritania",
  "mauritius",
  "mexico",
  "moldova",
  "monaco",
  "mongolia",
  "montenegro",
  "morocco",
  "namibia",
  "nepal",
  "netherlands",
  "new zealand",
  "nicaragua",
  "niger",
  "nigeria",
  "north macedonia",
  "norway",
  "oman",
  "pakistan",
  "panama",
  "papua new guinea",
  "paraguay",
  "peru",
  "philippines",
  "poland",
  "portugal",
  "qatar",
  "romania",
  "russia",
  "rwanda",
  "saint lucia",
  "saint vincent and the grenadines",
  "san marino",
  "saudi arabia",
  "senegal",
  "serbia",
  "seychelles",
  "singapore",
  "slovakia",
  "slovenia",
  "somalia",
  "south africa",
  "spain",
  "sri lanka",
  "sudan",
  "suriname",
  "sweden",
  "switzerland",
  "taiwan*",
  "tanzania",
  "thailand",
  "togo",
  "trinidad and tobago",
  "tunisia",
  "turkey",
  "uganda",
  "ukraine",
  "uae",
  "uk",
  "uruguay",
  "usa",
  "uzbekistan",
  "venezuela",
  "vietnam",
  "zambia",
  "zimbabwe",
  "dominica",
  "grenada",
  "mozambique",
  "syria",
  "timor-leste",
  "belize",
  "laos",
  "libya",
  "west bank and gaza",
  "guinea-bissau",
  "mali",
  "saint kitts and nevis",
  "kosovo"
];

export default countries_list;
